version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: docker-rails-api-generator
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle:/bundle:delegated
      - node_modules:/app/node_modules:delegated

volumes:
  bundle:
  node_modules: